#!/usr/bin/env bash
# deploy.sh — clone/pull AI SENTINEL from GitHub and deploy to /opt
# Usage:
#   First time:  sudo bash deploy.sh
#   Update:      sudo bash deploy.sh --pull
set -euo pipefail

REPO="engrossedadvisory/ai-sentinel"
REPO_URL="https://github.com/${REPO}.git"
INSTALL_DIR="/opt/ai-sentinel"
SERVICE_NAME="ai-sentinel"

# ── Require root ──────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo "Run as root:  sudo bash deploy.sh [--pull]" >&2
  exit 1
fi

PULL_ONLY=false
[[ "${1:-}" == "--pull" ]] && PULL_ONLY=true

# ── Docker compose detection ──────────────────────────────────────────────
echo "==> Detecting Docker Compose…"
if docker compose version &>/dev/null 2>&1; then
  COMPOSE_BIN="docker compose"
  echo "    ✓ docker compose (v2)"
elif command -v docker-compose &>/dev/null; then
  COMPOSE_BIN="docker-compose"
  echo "    ✓ docker-compose (v1)"
else
  echo "ERROR: Neither 'docker compose' nor 'docker-compose' found." >&2
  echo "       Install Docker: https://docs.docker.com/engine/install/" >&2
  exit 1
fi

# ── Ensure Docker daemon is healthy ──────────────────────────────────────
echo "==> Checking Docker daemon…"
if ! docker info &>/dev/null 2>&1; then
  echo "    Docker not responding — restarting daemon…"
  systemctl restart docker
  sleep 4
fi
echo "    ✓ Docker daemon OK"

# ── Port detection ────────────────────────────────────────────────────────
# Checks: ss (host), /proc/net/tcp, lsof, AND Docker container port table
port_in_use() {
  local port=$1

  # ss — reliable on all modern Linux
  ss -tlnH 2>/dev/null | awk '{print $4}' | grep -q ":${port}$" && return 0

  # /proc/net/tcp (hex port) — kernel-level, always present
  local hex; hex=$(printf '%04X' "${port}")
  grep -qi ":${hex} " /proc/net/tcp  2>/dev/null && return 0
  grep -qi ":${hex} " /proc/net/tcp6 2>/dev/null && return 0

  # lsof — optional but thorough
  command -v lsof &>/dev/null && lsof -iTCP:"${port}" -sTCP:LISTEN -t &>/dev/null 2>&1 && return 0

  # Docker port table — catches ports held by containers (running OR stopped)
  docker ps -a --format '{{.Ports}}' 2>/dev/null \
    | grep -qE "(0\.0\.0\.0|::):${port}->" && return 0

  return 1
}

find_free_port() {
  local port=$1
  while port_in_use "${port}"; do
    echo "    ⚠ Port ${port} in use — trying $((port+1))…" >&2
    port=$((port + 1))
  done
  echo "${port}"
}

echo "==> Scanning for available ports…"
FRONTEND_PORT=$(find_free_port 3000)
BACKEND_PORT=$(find_free_port 8000)
echo "    ✓ Dashboard  → port ${FRONTEND_PORT}"
echo "    ✓ API        → port ${BACKEND_PORT}"

# ── GitHub auth ───────────────────────────────────────────────────────────
echo "==> Checking GitHub authentication…"
if command -v gh &>/dev/null && gh auth status &>/dev/null 2>&1; then
  echo "    ✓ gh CLI authenticated"
  GH_TOKEN="$(gh auth token 2>/dev/null || true)"
  [[ -n "${GH_TOKEN}" ]] && REPO_URL="https://oauth2:${GH_TOKEN}@github.com/${REPO}.git"
else
  echo "    ⚠ gh CLI not authed — using public HTTPS"
fi

# ── Clone or pull ─────────────────────────────────────────────────────────
if [[ "${PULL_ONLY}" == "true" ]]; then
  [[ ! -d "${INSTALL_DIR}/.git" ]] && { echo "ERROR: not a git repo — run without --pull first" >&2; exit 1; }
  echo "==> Pulling latest…"
  git -C "${INSTALL_DIR}" pull --rebase origin main
else
  if [[ -d "${INSTALL_DIR}/.git" ]]; then
    echo "==> Updating existing install…"
    git -C "${INSTALL_DIR}" pull --rebase origin main
  else
    echo "==> Cloning ${REPO} → ${INSTALL_DIR}…"
    git clone "${REPO_URL}" "${INSTALL_DIR}"
  fi
fi
echo "    ✓ Code ready"

# ── Write docker-compose.override.yml with the detected ports ─────────────
# This file is read automatically by docker compose and takes full precedence
# over docker-compose.yml — no env var substitution, no ambiguity.
OVERRIDE="${INSTALL_DIR}/docker-compose.override.yml"
cat > "${OVERRIDE}" << OVERRIDE_EOF
# Auto-generated by deploy.sh — do not edit manually, re-run deploy.sh to update
services:
  backend:
    ports:
      - "${BACKEND_PORT}:8000"
  frontend:
    ports:
      - "${FRONTEND_PORT}:80"
OVERRIDE_EOF
echo "    ✓ Port override written → ${OVERRIDE}"

# ── Persistent data directory ─────────────────────────────────────────────
mkdir -p "${INSTALL_DIR}/data"
chmod 700 "${INSTALL_DIR}/data"

# ── Create .env if it doesn't exist ──────────────────────────────────────
ENV_FILE="${INSTALL_DIR}/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "==> Creating ${ENV_FILE}…"
  cat > "${ENV_FILE}" << 'ENVEOF'
# ─────────────────────────────────────────────────────────────────
#  AI SENTINEL — environment configuration
#  "AI acts. SENTINEL answers."
#
#  Edit this file then restart the service:
#    sudo systemctl restart ai-sentinel
# ─────────────────────────────────────────────────────────────────

# ── Global AI fallback ────────────────────────────────────────────
# Provider: none | claude | openai | gemini | ollama
AI_PROVIDER=none
AI_MODEL=

# ── API keys ──────────────────────────────────────────────────────
# Keys can also be set at runtime via Brain Center → Provider Keys tab
ANTHROPIC_API_KEY=
OPENAI_API_KEY=
GEMINI_API_KEY=

# ── Ollama (local / on-premise) ───────────────────────────────────
OLLAMA_HOST=http://localhost:11434

# ── Per-brain configuration (overrides global above) ─────────────
# BRAIN_TRIAGE_PROVIDER=claude
# BRAIN_TRIAGE_MODEL=claude-haiku-3-5
#
# BRAIN_DETECTION_PROVIDER=claude
# BRAIN_DETECTION_MODEL=claude-sonnet-4-5
#
# BRAIN_RISK_PROVIDER=ollama
# BRAIN_RISK_MODEL=llama3.2
#
# BRAIN_POLICY_PROVIDER=gemini
# BRAIN_POLICY_MODEL=gemini-2.0-flash
#
# BRAIN_MITIGATION_PROVIDER=openai
# BRAIN_MITIGATION_MODEL=gpt-4o
ENVEOF
  echo "    ✓ Created ${ENV_FILE}"
fi
chmod 600 "${ENV_FILE}"

# ── systemd service ───────────────────────────────────────────────────────
echo "==> Writing systemd service…"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
cat > "${SERVICE_FILE}" << SVCEOF
[Unit]
Description=AI SENTINEL — AI Agent Governance Platform
Documentation=https://github.com/${REPO}
Requires=docker.service
After=docker.service network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=-${INSTALL_DIR}/.env
ExecStartPre=-${COMPOSE_BIN} down --remove-orphans
ExecStart=${COMPOSE_BIN} up -d --build
ExecStop=${COMPOSE_BIN} down --remove-orphans
ExecReload=${COMPOSE_BIN} pull && ${COMPOSE_BIN} up -d --build
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}"

# ── Done ──────────────────────────────────────────────────────────────────
HOST_IP=$(hostname -I | awk '{print $1}')
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║       AI SENTINEL — Deployment Complete              ║"
echo "║       AI acts. SENTINEL answers.                     ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  Install dir : ${INSTALL_DIR}"
echo "  Config      : ${ENV_FILE}"
echo "  Port config : ${OVERRIDE}"
echo "  GitHub      : https://github.com/${REPO}"
echo ""
echo "  Access URLs:"
echo "    Dashboard  → http://${HOST_IP}:${FRONTEND_PORT}"
echo "    API / docs → http://${HOST_IP}:${BACKEND_PORT}/docs"
echo ""
echo "  Next steps:"
echo "    sudo nano ${ENV_FILE}                    # set AI provider keys"
echo "    sudo systemctl start ${SERVICE_NAME}     # start the platform"
echo ""
echo "  Manage:"
echo "    sudo systemctl stop    ${SERVICE_NAME}"
echo "    sudo systemctl restart ${SERVICE_NAME}"
echo "    sudo journalctl -u ${SERVICE_NAME} -f"
echo ""
echo "  Update from GitHub:"
echo "    sudo bash ${INSTALL_DIR}/deploy.sh --pull"
echo ""
